### ISSUE TITLE
Returns same data as the input

### ISSUE THREAD

**Issue by ctapobep** [hsiaocy/Beads#1]
I tried to use the `test()` method and instead of this:

```
sig = np.cos(2*np.pi*7*t) + np.sin(3*np.pi*7*t+300*t)
```

I entered my chromatogram. But in the end the original signal and the result are almost the same. Do I need to tune the params? I don't understand the math behind it yet, so I was hoping that the algorithm would "just work". 

Here are these chromatograms in 1 plot (you see only 1 line because they are very similar):
![figure_1](https://user-images.githubusercontent.com/702510/46905754-afbaba80-cf00-11e8-8dda-dd6e73afb1ec.png)

And here is `plt.plot(domain, sig - x.squeeze(), 'g')`:

![diff](https://user-images.githubusercontent.com/702510/46905762-c82ad500-cf00-11e8-975e-d1c5140bf954.png)

**Comment by ctapobep** [comment]
Noticed a cut-off frequency in the code, which depended on the signal length. Changing it to 0.9 did have an effect: 
![fc09](https://user-images.githubusercontent.com/702510/46908731-df34eb80-cf2f-11e8-9c52-f289caa437e4.png)

Though still not satisfactory at the beginning and at the end of the chromatogram. Is this fixable with tuning of other params or these artifacts can't be fixed with BEADS?

**Comment by hsiaocy** [comment]
Hi ctapobep, 
Thanks for adopting this algorithm, but I'm regretfully to say that I didn't spend much time on this algorithm. Perhaps you could try different parameters because I tried it originally for comparing against Wavelet Transform and Hilbert-Huang Transform in the electrocardiogram.
That's why I'm so sorry that I cannot explain detail for you.

**Comment by ctapobep** [comment]
Ok, got it, thanks. Did you decide in the end to use BEADS instead of other alternatives for baseline correction?

**Comment by hsiaocy** [comment]
Yes, for my research of electrocardiogram pre-processing, I eventually used HHT because it speeds up the whole working flow.
I have no base about chromatogram but just giving you a suggestion.
