### ISSUE TITLE
A problem in your test method

### ISSUE THREAD

**Issue by mrchipset** [hsiaocy/Beads#2]
Hello,
I think you make a mistake in your function return value arrange in Line 167. Your code is `  x, f, cost = beads(y=sig, d=d, fc=fc, r=r, lam0=lam0, lam1=lam1, lam2=lam2)`. But refer from the definition in Line 101, it should be `x, cost, f = beads(y=sig, d=d, fc=fc, r=r, lam0=lam0, lam1=lam1, lam2=lam2)`.

**Comment by hsiaocy** [comment]
Yes, you are right! 
In line 167, the test is not correct, and I will amend this, thank you!
