### ISSUE TITLE
Different output between python and Matlab

### ISSUE THREAD

**Issue by sank96** [hsiaocy/Beads#3]
Hi, 
I used beads function on Matlab and it works perfectly. 
After that I needed to translate the code in Python and this function doesn't work as Matlab ones.

I attach two screenshots of the same input, with two different output.

**matlab comparison**
<img width="562" alt="figure_matlab" src="https://user-images.githubusercontent.com/16799929/58814580-479f1d00-8626-11e9-82cb-f70328df0872.png">

**Python comparison**
![figure_python](https://user-images.githubusercontent.com/16799929/58814595-4c63d100-8626-11e9-808d-52e274b9d7c9.png)

**Comment by hsiaocy** [comment]
Hi @mett96,
Thanks for asking this issue.
Would you mind send me your input data? because I want to try and figure out the problem.
Thansk!

**Comment by sank96** [comment]
Hi @hsiaocy.
thanks in advance

The input data is taken by this file (it is a csv file but github doesn't support this extension)
[test.txt](https://github.com/hsiaocy/Beads/files/3251251/test.txt)

I compute data into algorithm with a window of 100 elements, after that I shift it.

The parameters that I used are:
```
fc = 0.006
d = 1
r = 6

amp = 0.8
lam0 = 0.5 * amo
lam1 = 5 * amp
lam2 = 4 * amp

Nit = 3
pen = 'L1_v2'
```

**Comment by hsiaocy** [comment]
Hi @mett96,
Sorry for the late.
I've tried to fix the bug, the syntax differentiates from the Matlab the matrix left division, and the result as shown below.
![test20190608](https://user-images.githubusercontent.com/18674506/59142735-ecd63e80-89f4-11e9-9553-7c4da763b17b.png)
Hope it helps you!

**Comment by sank96** [comment]
Yeah!!! 

Now it work perfectly. 
Thank you very much!!!
